---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: camera-app
  labels:
    app: camera-app
spec:
  selector:
    matchLabels:
      app: camera-app
  template:
    metadata:
      labels:
        app: camera-app
    spec:
      containers:
      - name: camera-app
        image: natalieserrino/camera-app:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: http
        volumeMounts:
        - mountPath: /dev/video0
          name: dev-video0
        securityContext:
          privileged: true 
      volumes:
      - name: dev-video0
        hostPath:
          path: /dev/video0          
---
apiVersion: v1
kind: Service
metadata:
  name: camera-app
spec:
  selector:
    app: camera-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      name: http